SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

GAME_WIDTH = 595
GAME_HEIGHT = 720

BORDER_WIDTH = 348
BORDER_HEIGHT = 720
BORDER_COLOR = 'lavender'

BACKGROUND_COLOR = '#494d7e'

MENU_FONT = 'graphics\\fonts\\Pacifico-Regular.ttf'
MENU_FONT_SIZE = 80
MENU_COLOR = 'white'

SPAWN_LANE1 = BORDER_WIDTH + ((1/6)*GAME_WIDTH)
SPAWN_LANE2 = BORDER_WIDTH + ((2/6)*GAME_WIDTH)
SPAWN_LANE3 = BORDER_WIDTH + ((3/6)*GAME_WIDTH)
SPAWN_LANE4 = BORDER_WIDTH + ((4/6)*GAME_WIDTH)
SPAWN_LANE5 = BORDER_WIDTH + ((5/6)*GAME_WIDTH)